#adapted from example in docker documentation
version: '3'

services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis


  web:
    build: .
    volumes:
       - .:/code
    links:
       - redis
    ports:
       - 80:8000
    environment:
       - REDIS_URL=redis://cache
       - NODE_ENV=development
       - RHOST=redis
       - PORT=8000
         #    user: "1000:1000" 
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    
