# Generated by Django 2.2.5 on 2019-11-15 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=60)),
                ('recipeDescription', models.CharField(max_length=500)),
                ('foodImage', models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d/')),
                ('foodCategory', models.CharField(choices=[('Asia', 'Asian'), ('Amer', 'American'), ('Chin', 'Chinese'), ('Indi', 'Indian'), ('Ital', 'Italian'), ('Japa', 'Japanese'), ('Mexi', 'Mexican'), ('Thai', 'Thai'), ('Gree', 'Greek'), ('Othe', 'Other')], max_length=4)),
                ('recipeUrl', models.URLField(blank=True, max_length=240)),
                ('recipeDirections', models.CharField(blank=True, max_length=240)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=60)),
                ('amount', models.CharField(max_length=30)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Recipe')),
            ],
        ),
    ]
